# Generated by Django 5.1.15 on 2026-05-14 10:45

from django.db import migrations, models


def backfill_started_at(apps, schema_editor):
    ProgressTracking = apps.get_model("interviews", "ProgressTracking")
    for progress in ProgressTracking.objects.filter(started_at__isnull=True).exclude(state="locked").iterator():
        progress.started_at = progress.unlocked_at or progress.created_at
        progress.save(update_fields=["started_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progresstracking',
            name='state',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('current', 'Current'), ('passed', 'Threshold Cleared'), ('failed', 'Below Company Benchmark'), ('expired', 'Expired')], default='locked', max_length=20),
        ),
        migrations.RunPython(backfill_started_at, migrations.RunPython.noop),
    ]
